version: '3.8'
services:
  app:
    build: .
    container_name: poc-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - LOG_LEVEL=INFO
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2g"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
